export const ukr = {
    uk: {
        translation: {
            "Search by book title": "Пошук за назвою книги",
            "All books": "Всі книги",
            "from $0 to $15": "від $0 до $15",
            "from $15 to $30": "від $15 до $30",
            "more than $30": "більше ніж $30",
            Error: "Помилка",
            "Book cover": "Обкладинка книги",
            "Enter your login and password or sign up, please :)":
                "Введіть ваш логін та пароль або зареєструйтесь, будь ласка :)",
            View: "Відкрити",
            "Books not found...": "Книги не знайдено...",
            Home: "Головна",
            Book: "Книга",
            Cart: "Кошик",
            About: "Про нас",
            "Log out": "Вийти",
            "Log in": "Увійти",
            "Sign up": "Реєстрація",
            "Online Bookstore": "Онлайн Книжковий Магазин",
            "At Book Store, we invite you to embark on a journey through the enchanting realms of literature, where every page unfolds a new adventure. Our online bookstore is a haven for book enthusiasts, offering an extensive and diverse collection that caters to every taste and preference.":
                "У нашому книжковому магазині ми запрошуємо вас вирушити у подорож через чарівні світи літератури, де кожна сторінка відкриває нову пригоду. Наш онлайн-книжковий магазин - це рай для книголюбів, що пропонує великий і різноманітний асортимент, який задовольнить будь-який смак і вподобання.",
            "Explore a World of Books: From timeless classics that have shaped generations to the latest page-turners captivating readers worldwide, our curated selection spans various genres, ensuring there's something for everyone. Immerse yourself in fiction, get inspired by non-fiction, or let the little ones discover magical worlds in our children's section.":
                "Досліджуйте світ книг: Від вічної класики, що формувала покоління, до останніх бестселерів, які захоплюють читачів у всьому світі, наша ретельно підібрана колекція охоплює різні жанри, гарантуючи, що кожен знайде щось для себе. Пориньте у художню літературу, надихайтесь науково-популярною літературою або дозвольте малюкам відкрити чарівні світи у нашому дитячому відділі.",
            "Visit Our Imaginary Storefront: While our physical address is purely fictional, the warmth and joy of exploring our virtual bookstore are very real. Wander through the digital aisles, browse book covers, and read engaging summaries - all from the comfort of your home.":
                "Відвідайте наш вигаданий магазин: Хоча наша фізична адреса є суто вигаданою, тепло і радість від дослідження нашого віртуального книжкового магазину дуже реальні. Подорожуйте цифровими проходами, переглядайте обкладинки книг і читайте захоплюючі анотації - все з комфорту вашого дому.",
            "Customer Support: Have a question or need assistance? Our friendly and fictional customer support team is just a phone call away.":
                "Підтримка клієнтів: У вас є питання або потрібна допомога? Наша дружня і вигадана команда підтримки клієнтів завжди на зв'язку.",
            "Dial 555-123-4567 for personalized assistance or drop us an email at info@bookhaven.com.":
                "Зателефонуйте 555-123-4567 для персональної допомоги або напишіть нам на info@bookhaven.com.",
            "Online Ordering Made Easy: Experience the convenience of online shopping with our user-friendly platform. Browse, add to your cart, and securely check out - all in a few clicks. We ship to imaginary locations worldwide!":
                "Замовлення онлайн стало простішим: Відчуйте зручність онлайн-шопінгу з нашою зручною платформою. Переглядайте, додавайте до кошика і безпечно оформлюйте замовлення - все у кілька кліків. Ми доставляємо у вигадані місця по всьому світу!",
            "Whether you're an avid reader, a casual browser, or a gift-giver in search of the perfect literary present, Book Haven is your destination for literary bliss. Discover the joy of reading with us – where every book is an adventure waiting to be unfolded. Happy reading! 📖✨":
                "Чи ви затятий читач, випадковий переглядач або шукач подарунків у пошуках ідеального літературного презенту, Book Haven - це ваш пункт призначення для літературного блаженства. Відкрийте для себе радість читання з нами - де кожна книга - це пригода, що чекає на розкриття. Щасливого читання! 📖✨",

            "Email address": "Адреса електронної пошти",
            Password: "Пароль",
            Back: "Назад",
            "Log in now to unlock your exclusive access to content and offers":
                "Увійдіть зараз, щоб отримати доступ до контенту та пропозицій",
            "Don't have an account?": "Не маєте облікового запису?",
            "Register Now": "Зареєструйтесь зараз",
            Register: "Реєстрація",
            "Your name": "Ваше ім'я",
            "Oops, something went wrong... Error 404":
                "Ой, щось пішло не так... Помилка 404",
            "Go to books": "Перейти до книг",
            "Book author": "Автор книги",
            "Book level": "Складність",
            "Short description": "Короткий опис",
            "Full description": "Повний опис",
            Price: "Ціна",
            Quantity: "Кількість",
            Total: "Сума",
            "Add to cart": "Додати до кошика",
            "The book has not been selected yet...🕵️": "Книга ще не вибрана...🕵️",
            Close: "Закрити",
            Remove: "Видалити",
            "Your cart is empty...": "Ваш кошик порожній...",
            Title: "Назва",
            "Total Price": "Загальна ціна",
            "Total Sum": "Повна вартість",
            Purchase: "Купити",
            "JavaScript is the programming language of the web and is used by more software developers today than any other programming language.":
                "JavaScript — це мова веб-програмування, яка сьогодні використовується більшою кількістю розробників програмного забезпечення, ніж будь-яка інша мова програмування.",
            "Building robust apps starts with creating clean code. In this book, you'll explore techniques for doing this by learning everything from the basics of JavaScript through to the practices of clean code. You'll write functional, intuitive, and maintainable code while also understanding how your code affects the end user and the wider community.":
                "Створення надійних програм починається зі створення чистого коду. У цій книзі ви дослідите методи, як це зробити, вивчаючи все: від основ JavaScript до практик чистого коду. Ви будете писати функціональний, інтуїтивно зрозумілий код, який зручно підтримувати, а також розумітимете, як ваш код впливає на кінцевого користувача та ширшу спільноту.",
            "JavaScript is the little scripting language that could. Once used chiefly to add interactivity to web browser windows, JavaScript is now a primary building block of powerful and robust applications.":
                "JavaScript — це маленька мова сценаріїв, яка може. Колись JavaScript використовувався головним чином для додавання інтерактивності вікнам веб-браузера, а зараз є основним будівельним блоком потужних і надійних програм.",
            "If you want to learn how to build efficient React applications, this is your book.":
                "Якщо ви хочете навчитися створювати ефективні програми React, це ваша книга.",
            "Hit the ground running with React, the open source technology from Facebook for building rich web applications fast.":
                "Почніть працювати з React, технологією з відкритим кодом від Facebook для швидкого створення багатофункціональних веб-додатків.",
            "If you're a web designer or app developer interested in sophisticated page styling, improved accessibility, and less time and effort expended, this book is for you.":
                "Якщо ви веб-дизайнер або розробник додатків, зацікавлений у складному стилі сторінок, покращеній доступності та меншій витраті часу та зусиль, ця книга для вас.",
            "Your code is a testament to your skills as a developer. No matter what language you use, code should be clean, elegant, and uncluttered.":
                "Ваш код є свідченням ваших навичок розробника. Незалежно від того, якою мовою ви користуєтеся, код має бути чистим, елегантним і незавантаженим.",
            "This book will demystify Angular as a framework, as well as provide clear instructions and examples on how to get started with writing scalable Angular applications.":
                "Ця книга демістифікує Angular як фреймворк, а також надасть чіткі інструкції та приклади того, як почати писати масштабовані програми Angular.",
            "The popularity of REST in recent years has led to tremendous growth in almost-RESTful APIs that don’t include many of the architecture’s benefits.":
                "Популярність REST в останні роки призвела до величезного зростання майже повних REST API, які не містять багатьох переваг архітектури.",
            "Universal Design for Web Applications teaches you how to build websites that are more accessible to people with disabilities and explains why doing so is good business.":
                "Універсальний дизайн для веб-додатків навчить вас створювати веб-сайти, які будуть більш доступними для людей з обмеженими можливостями, і пояснює, чому це є хорошим бізнесом.",
            "Web apps would run much better if heavy calculations could be performed in the background, rather than compete with the user interface.":
                "Веб-програми працювали б набагато краще, якби важкі обчислення могли виконуватися у фоновому режимі, а не конкурувати з інтерфейсом користувача.",
            "Until recently, creating desktop-like applications in the browser meant using inefficient Ajax or Comet technologies to communicate with the server.":
                "До недавнього часу створення програм, схожих на настільні комп’ютери, у браузері означало використання неефективних технологій Ajax або Comet для зв’язку із сервером.",
            "Ajax applications should be open yet secure. Far too often security is added as an afterthought. Potential flaws need to be identified and addressed right away.":
                "Програми Ajax мають бути відкритими, але безпечними. Занадто часто безпека додається позаду. Необхідно негайно виявити й усунути потенційні недоліки.",
            "Track, branch, merge, and manage code revisions with Git, the free and open source distributed version control system.":
                "Відстежуйте, розгалужуйте, об’єднуйте та керуйте змінами коду за допомогою Git, безкоштовної розподіленої системи керування версіями з відкритим кодом.",
            "Manage your data with a system designed to support modern application development.":
                "Керуйте своїми даними за допомогою системи, розробленої для підтримки розробки сучасних програм.",
            "Learn the basics of Git in a simple, visual, and tangible manner.":
                "Вивчіть основи Git у простий, візуальний і відчутний спосіб.",
            "Using Scalable Vector Graphics (SVG) for illustrations only scratches the surface of this format’s potential on the web.":
                "Використання масштабованої векторної графіки (SVG) для ілюстрацій лише дряпає поверхню потенціалу цього формату в Інтернеті.",
            "SVG is extremely powerful, with its reduced HTTP requests and crispness on any display.":
                "SVG є надзвичайно потужним із його зменшеною кількістю запитів HTTP та чіткістю на будь-якому дисплеї.",
            "You can do more with Git than just build software.":
                "З Git ви можете робити більше, ніж просто створювати програмне забезпечення.",
            "Take your web development skills from browser to server with Node—and learn how to write fast, highly scalable network applications on this JavaScript-based platform.":
                "Перенесіть свої навички веб-розробки від веб-переглядача до сервера за допомогою Node — і навчіться писати швидкі, високомасштабовані мережеві програми на цій платформі на основі JavaScript.",
            "If you know how to use JavaScript in the browser, you already have the skills you need to put JavaScript to work on back-end servers with Node.":
                "Якщо ви знаєте, як використовувати JavaScript у браузері, у вас уже є навички, необхідні для роботи JavaScript на внутрішніх серверах із Node.",
            "JavaScript is the programming language of the web and is used by more software developers today than any other programming language. For nearly 25 years this best seller has been the go-to guide for JavaScript programmers. The seventh edition is fully updated to cover the 2020 version of JavaScript, and new chapters cover classes, modules, iterators, generators, Promises, async/await, and metaprogramming. You’ll find illuminating and engaging example code throughout. This book is for programmers who want to learn JavaScript and for web developers who want to take their understanding and mastery to the next level. It begins by explaining the JavaScript language itself, in detail, from the bottom up. It then builds on that foundation to cover the web platform and Node.js.":
                "JavaScript — це мова веб-програмування, яка сьогодні використовується більшою кількістю розробників програмного забезпечення, ніж будь-яка інша мова програмування. Протягом майже 25 років цей бестселер був основним посібником для програмістів на JavaScript. Сьоме видання повністю оновлено, щоб охопити версію JavaScript 2020, а нові розділи охоплюють класи, модулі, ітератори, генератори, Promises, async/await і метапрограмування. Усюди ви знайдете яскравий і захоплюючий приклад коду. Ця книга призначена для програмістів, які хочуть вивчити JavaScript, і для веб-розробників, які хочуть вивести своє розуміння та майстерність на новий рівень. Він починається з детального пояснення самої мови JavaScript знизу вгору. Потім він спирається на цю основу, щоб охопити веб-платформу та Node.js.",
            "Building robust apps starts with creating clean code. In this book, you'll explore techniques for doing this by learning everything from the basics of JavaScript through to the practices of clean code. You'll write functional, intuitive, and maintainable code while also understanding how your code affects the end user and the wider community. The book starts with popular clean-coding principles such as SOLID, and the Law of Demeter (LoD), along with highlighting the enemies of writing clean code such as cargo culting and over-management. You'll then delve into JavaScript, understanding the more complex aspects of the language. Next, you'll create meaningful abstractions using design patterns, such as the Class Pattern and the Revealing Module Pattern. You'll explore real-world challenges such as DOM reconciliation, state management, dependency management, and security, both within browser and server environments. Later, you'll cover tooling and testing methodologies and the importance of documenting code. Finally, the book will focus on advocacy and good communication for improving code cleanliness within teams or workplaces, along with covering a case study for clean coding. By the end of this book, you'll be well-versed with JavaScript and have learned how to create clean abstractions, test them, and communicate about them via documentation.":
                "Створення надійних програм починається зі створення чистого коду. У цій книзі ви дослідите методи, як це зробити, вивчаючи все: від основ JavaScript до практик чистого коду. Ви будете писати функціональний, інтуїтивно зрозумілий код, який зручно підтримувати, а також розумітимете, як ваш код впливає на кінцевого користувача та ширшу спільноту. Книга починається з популярних принципів чистого кодування, таких як SOLID і Закон Деметри (LoD), а також висвітлює ворогів написання чистого коду, таких як культ вантажу та надмірне управління. Потім ви заглибитесь у JavaScript, зрозуміючи складніші аспекти мови. Далі ви створите значущі абстракції за допомогою шаблонів проектування, таких як шаблон класу та шаблон модуля розкриття. Ви досліджуватимете проблеми реального світу, такі як узгодження DOM, керування станом, керування залежностями та безпека як у середовищі браузера, так і на сервері. Пізніше ви розглянете інструменти та методології тестування, а також важливість документування коду. Нарешті, книга буде зосереджена на адвокації та гарній комунікації для покращення чистоти коду в командах або на робочих місцях, а також висвітлюватиме практичне дослідження щодо чистого кодування. До кінця цієї книги ви будете добре знайомі з JavaScript і навчитеся створювати чисті абстракції, тестувати їх і повідомляти про них через документацію.",
            "JavaScript is the little scripting language that could. Once used chiefly to add interactivity to web browser windows, JavaScript is now a primary building block of powerful and robust applications. In this practical book, new and experienced JavaScript developers will learn how to use this language to create APIs as well as web, mobile, and desktop applications. Author and engineering leader Adam D. Scott covers technologies such as Node.js, GraphQL, React, React Native, and Electron. Ideal for developers who want to build full stack applications and ambitious web development beginners looking to bootstrap a startup, this book shows you how to create a single CRUD-style application that will work across several platforms.":
                "JavaScript — це маленька мова сценаріїв, яка може. Колись JavaScript використовувався головним чином для додавання інтерактивності вікнам веб-браузера, а зараз є основним будівельним блоком потужних і надійних програм. У цій практичній книзі нові та досвідчені розробники JavaScript навчаться використовувати цю мову для створення API, а також веб-, мобільних і настільних програм. Автор та лідер інженерів Адам Д. Скотт охоплює такі технології, як Node.js, GraphQL, React, React Native та Electron. Ця книга ідеально підходить для розробників, які хочуть створити повний стек додатків, і амбітних початківців веб-розробників, які прагнуть запустити стартап. Ця книга покаже, як створити єдину програму в стилі CRUD, яка працюватиме на кількох платформах.",
            "If you want to learn how to build efficient React applications, this is your book. Ideal for web developers and software engineers who understand how JavaScript, CSS, and HTML work in the browser, this updated edition provides best practices and patterns for writing modern React code. No prior knowledge of React or functional JavaScript is necessary. With their learning road map, authors Alex Banks and Eve Porcello show you how to create UIs that can deftly display changes without page reloads on large-scale, data-driven websites. You’ll also discover how to work with functional programming and the latest ECMAScript features. Once you learn how to build React components with this hands-on guide, you’ll understand just how useful React can be in your organization.":
                "Якщо ви хочете навчитися створювати ефективні програми React, це ваша книга. Це оновлене видання ідеально підходить для веб-розробників та інженерів програмного забезпечення, які розуміють, як JavaScript, CSS і HTML працюють у браузері. Це оновлене видання містить найкращі практики та шаблони для написання сучасного коду React. Попередні знання React або функціонального JavaScript не потрібні. Автори Алекс Бенкс та Єва Порчелло в своїй навчальній карті показують, як створювати інтерфейси користувача, які можуть спритно відображати зміни без перезавантаження сторінок на великомасштабних веб-сайтах, керованих даними. Ви також дізнаєтеся, як працювати з функціональним програмуванням і найновішими функціями ECMAScript. Коли ви навчитеся створювати компоненти React за допомогою цього практичного посібника, ви зрозумієте, наскільки React може бути корисним у вашій організації.",
            "Hit the ground running with React, the open source technology from Facebook for building rich web applications fast. Updated for the latest React release, the second edition of this hands-on guide shows you how to build React components and organize them into maintainable large-scale apps. If you're familiar with JavaScript syntax, you're ready to get started. Through the course of this book, author Stoyan Stefanov helps web developers and programmers build a complete single-page application. You'll quickly learn why some developers consider React the key to the web app development puzzle.":
                "Почніть працювати з React, технологією з відкритим кодом від Facebook для швидкого створення багатофункціональних веб-додатків. Друге видання цього практичного посібника, оновлене для останнього випуску React, показує, як створювати компоненти React і організовувати їх у зручні для обслуговування великомасштабні програми. Якщо ви знайомі з синтаксисом JavaScript, ви готові розпочати роботу. Ознайомлюючись із цією книгою, автор Стоян Стефанов допомагає веб-розробникам і програмістам створити повну односторінкову програму. Ви швидко дізнаєтеся, чому деякі розробники вважають React ключем до головоломки розробки веб-додатків.",
            "If you're a web designer or app developer interested in sophisticated page styling, improved accessibility, and less time and effort expended, this book is for you. This revised fifth edition provides a comprehensive guide to CSS implementation along with a thorough review of the latest CSS specifications. Authors Eric Meyer and Estelle Weyl show you how to improve user experience, speed development, avoid potential bugs, and add life and depth to your applications through layout, transitions and animations, borders, backgrounds, text properties, and many other tools and techniques.":
                "Якщо ви веб-дизайнер або розробник додатків, зацікавлений у складному стилі сторінок, покращеній доступності та меншій витраті часу та зусиль, ця книга для вас. Це переглянуте п’яте видання містить вичерпний посібник із впровадження CSS разом із детальним оглядом останніх специфікацій CSS. Автори Ерік Майєр і Естель Вейл показують вам, як покращити взаємодію з користувачем, пришвидшити розробку, уникнути потенційних помилок і додати життя та глибини вашим програмам за допомогою макета, переходів та анімації, рамок, фону, властивостей тексту та багатьох інших інструментів і прийомів.",
            "Your code is a testament to your skills as a developer. No matter what language you use, code should be clean, elegant, and uncluttered. By using test-driven development (TDD), you'll write code that's easy to understand, retains its elegance, and works for months, even years, to come. With this indispensable guide, you'll learn how to use TDD with three different languages: Go, JavaScript, and Python. Author Saleem Siddiqui shows you how to tackle domain complexity using a unit test-driven approach. TDD partitions requirements into small, implementable features, enabling you to solve problems irrespective of the languages and frameworks you use. With Learning Test-Driven Development at your side, you'll learn how to incorporate TDD into your regular coding practice.":
                "Ваш код є свідченням ваших навичок розробника. Незалежно від того, якою мовою ви користуєтеся, код має бути чистим, елегантним і незавантаженим. Використовуючи тестову розробку (TDD), ви напишете код, який буде простим для розуміння, збереже свою елегантність і працюватиме протягом місяців, навіть років. З цим незамінним посібником ви дізнаєтеся, як використовувати TDD з трьома різними мовами: Go, JavaScript і Python. Автор Салім Сіддікі показує вам, як боротися зі складністю домену за допомогою підходу, керованого модульним тестуванням. TDD розбиває вимоги на невеликі функції, які можна реалізувати, що дозволяє вирішувати проблеми незалежно від мов і фреймворків, які ви використовуєте. Завдяки програмі Learning Test-Driven Development ви навчитеся включати TDD у свою звичайну практику програмування.",
            "This book will demystify Angular as a framework, as well as provide clear instructions and examples on how to get started with writing scalable Angular applications. Angular: Up & Running covers most of the major pieces of Angular, but in a structured manner that is generally used in hands-on training. Each chapter takes one concept, and use examples to cover how it works. Problems to work on (with solutions) at the end of each chapter reinforce the learnings of each chapter and allow readers to really get hands-on with Angular.":
                "Ця книга демістифікує Angular як фреймворк, а також надасть чіткі інструкції та приклади того, як почати писати масштабовані програми Angular. Angular: Up & Running охоплює більшість основних частин Angular, але в структурованому вигляді, який зазвичай використовується під час практичного навчання. Кожен розділ містить одну концепцію та використовує приклади, щоб зрозуміти, як це працює. Проблеми для роботи (з рішеннями) у кінці кожного розділу підкріплюють знання кожного розділу та дозволяють читачам по-справжньому навчитися працювати з Angular.",
            "The popularity of REST in recent years has led to tremendous growth in almost-RESTful APIs that don’t include many of the architecture’s benefits. With this practical guide, you’ll learn what it takes to design usable REST APIs that evolve over time. By focusing on solutions that cross a variety of domains, this book shows you how to create powerful and secure applications, using the tools designed for the world’s most successful distributed computing system: the World Wide Web. You’ll explore the concepts behind REST, learn different strategies for creating hypermedia-based APIs, and then put everything together with a step-by-step guide to designing a RESTful Web API.":
                "Популярність REST в останні роки призвела до величезного зростання майже повних REST API, які не містять багатьох переваг архітектури. Завдяки цьому практичному посібнику ви дізнаєтесь, що потрібно для розробки корисних REST API, які з часом розвиваються. Зосереджуючись на рішеннях, що охоплюють різні сфери, ця книга показує, як створювати потужні та безпечні програми за допомогою інструментів, розроблених для найуспішнішої розподіленої обчислювальної системи світу: Всесвітньої павутини. Ви дослідите концепції, що лежать в основі REST, дізнаєтесь про різні стратегії створення API на основі гіпермедіа, а потім об’єднаєте все разом із покроковим посібником із розробки RESTful Web API.",
            "Universal Design for Web Applications teaches you how to build websites that are more accessible to people with disabilities and explains why doing so is good business. It takes more work up front, but the potential payoff is huge -- especially when mobile users need to access your sites. You'll discover how to use standards-based web technologies -- such as XHTML, CSS, and Ajax, along with video and Flash -- to develop applications for a wide range of users and a variety of devices, including the mobile Web. You'll also learn specifics about this target audience, especially the key over-50 age group, whose use of the Web is rapidly growing.":
                "Універсальний дизайн для веб-додатків навчить вас створювати веб-сайти, які будуть більш доступними для людей з обмеженими можливостями, і пояснює, чому це є хорошим бізнесом. Попередньо потрібно більше роботи, але потенційна вигода величезна, особливо коли мобільним користувачам потрібен доступ до ваших сайтів. Ви дізнаєтесь, як використовувати веб-технології, засновані на стандартах, такі як XHTML, CSS і Ajax, а також відео та Flash, щоб розробляти програми для широкого кола користувачів і різноманітних пристроїв, включаючи мобільний Інтернет. Ви також дізнаєтесь про особливості цієї цільової аудиторії, особливо про ключову вікову групу старше 50 років, чиє використання Інтернету швидко зростає.",
            "Web apps would run much better if heavy calculations could be performed in the background, rather than compete with the user interface. With this book, you’ll learn how to use Web Workers to run computationally intensive JavaScript code in a thread parallel to the UI. If you have an intermediate to advanced understanding of JavaScript— especially event handling and callbacks—you’re ready to tackle Web Workers with the tools in this example-driven guide.":
                "Веб-програми працювали б набагато краще, якби важкі обчислення могли виконуватися у фоновому режимі, а не конкурувати з інтерфейсом користувача. Завдяки цій книзі ви дізнаєтеся, як використовувати Web Workers для виконання інтенсивного коду JavaScript у потоці, паралельному інтерфейсу користувача. Якщо ви маєте знання про JavaScript на середньому або глибокому рівні, особливо про обробку подій і зворотні виклики, ви готові взятися за роботу з веб-працівниками за допомогою інструментів, наведених у цьому посібнику на основі прикладів.",
            "Until recently, creating desktop-like applications in the browser meant using inefficient Ajax or Comet technologies to communicate with the server. With this practical guide, you’ll learn how to use WebSocket, a protocol that enables the client and server to communicate with each other on a single connection simultaneously. No more asynchronous communication or long polling! For developers with a good grasp of JavaScript (and perhaps Node.js), author Andrew Lombardi provides useful hands-on examples throughout the book to help you get up to speed with the WebSocket API. You’ll also learn how to use WebSocket with Transport Layer Security (TLS).":
                "До недавнього часу створення програм, схожих на настільні комп’ютери, у браузері означало використання неефективних технологій Ajax або Comet для зв’язку із сервером. Завдяки цьому практичному посібнику ви дізнаєтесь, як використовувати WebSocket, протокол, який дозволяє клієнту та серверу одночасно спілкуватися один з одним через одне з’єднання. Більше жодного асинхронного зв’язку чи тривалого опитування! Для розробників, які добре розуміються на JavaScript (і, можливо, Node.js), автор Ендрю Ломбарді надає корисні практичні приклади в цій книзі, які допоможуть вам швидше освоїти WebSocket API. Ви також дізнаєтеся, як використовувати WebSocket із захистом транспортного рівня (TLS).",
            "Ajax applications should be open yet secure. Far too often security is added as an afterthought. Potential flaws need to be identified and addressed right away. This book explores Ajax and web application security with an eye for dangerous gaps and offers ways that you can plug them before they become a problem. By making security part of the process from the start, you will learn how to build secure Ajax applications and discover how to respond quickly when attacks occur. Securing Ajax Applications succinctly explains that the same back-and-forth communications that make Ajax so responsive also gives invaders new opportunities to gather data, make creative new requests of your server, and interfere with the communications between you and your customers. This book presents basic security techniques and examines vulnerabilities with JavaScript, XML, JSON, Flash, and other technologies -- vital information that will ultimately save you time and money.":
                "Програми Ajax мають бути відкритими, але безпечними. Занадто часто безпека додається позаду. Необхідно негайно виявити й усунути потенційні недоліки. У цій книзі досліджується безпека Ajax і веб-додатків з оглядом на небезпечні прогалини та пропонується способи їх усунення, перш ніж вони стануть проблемою. Зробивши безпеку частиною процесу з самого початку, ви навчитеся створювати безпечні програми Ajax і дізнаєтесь, як швидко реагувати на атаки. Захист додатків Ajax стисло пояснює, що ті самі зворотні зв’язки, які роблять Ajax таким чуйним, також дають зловмисникам нові можливості для збору даних, створення нових креативних запитів до вашого сервера та втручання у зв’язок між вами та вашими клієнтами. У цій книзі представлено основні методи безпеки та досліджено вразливості за допомогою JavaScript, XML, JSON, Flash та інших технологій — життєво важливої інформації, яка зрештою заощадить ваш час і гроші.",
            "Track, branch, merge, and manage code revisions with Git, the free and open source distributed version control system. Through a series of step-by-step tutorials, this practical guide quickly takes you from Git fundamentals to advanced techniques, and provides friendly yet rigorous advice for navigating Git's many functions. You'll learn how to work with everything from small to very large projects with speed and efficiency. In this third edition, authors Prem Kumar Ponuthorai and Jon Loeliger break down Git concepts using a modular approach. You'll start with the basics and fundamental philosophy of Git, followed by intermediate commands to help you efficiently supplement your daily development workflow. Finally, you'll learn advanced Git commands and concepts to understand how Git works under the hood.":
                "Відстежуйте, розгалужуйте, об’єднуйте та керуйте змінами коду за допомогою Git, безкоштовної розподіленої системи керування версіями з відкритим кодом. Завдяки серії покрокових посібників цей практичний посібник швидко переведе вас від основ Git до просунутих технік і надає дружні, але точні поради щодо навігації багатьма функціями Git. Ви навчитеся швидко й ефективно працювати з будь-якими проектами, від малих до дуже великих. У цьому третьому виданні автори Прем Кумар Понутораі та Джон Лоелігер розбивають концепції Git за допомогою модульного підходу. Ви почнете з основ і фундаментальної філософії Git, а потім проміжні команди, які допоможуть вам ефективно доповнити щоденний робочий процес розробки. Нарешті, ви дізнаєтесь про розширені команди та поняття Git, щоб зрозуміти, як Git працює під капотом.",
            "Manage your data with a system designed to support modern application development. Updated for MongoDB 4.2, the third edition of this authoritative and accessible guide shows you the advantages of using document-oriented databases. You’ll learn how this secure, high-performance system enables flexible data models, high availability, and horizontal scalability. Authors Shannon Bradshaw, Eoin Brazil, and Kristina Chodorow provide guidance for database developers, advanced configuration for system administrators, and use cases for a variety of projects. NoSQL newcomers and experienced MongoDB users will find updates on querying, indexing, aggregation, transactions, replica sets, ops management, sharding and data administration, durability, monitoring, and security.":
                "«Керуйте своїми даними за допомогою системи, розробленої для підтримки розробки сучасних додатків. Оновлене для MongoDB 4.2, третє видання цього авторитетного та доступного посібника показує вам переваги використання баз даних, орієнтованих на документи. Ви дізнаєтеся, як ця безпечна, високопродуктивна Система забезпечує гнучкі моделі даних, високу доступність і горизонтальну масштабованість. Автори Шеннон Бредшоу, Еоін Бразилія та Крістіна Чодоров надають вказівки для розробників баз даних, розширену конфігурацію для системних адміністраторів і приклади використання для різноманітних новачків у проектах і досвідчених користувачів MongoDB знайде оновлення щодо запитів, індексування, агрегації, транзакцій, наборів реплік, керування операціями, шардингу та адміністрування даних, довговічності, моніторингу та безпеки.",
            "Learn the basics of Git in a simple, visual, and tangible manner. With this practical book, author Anna Skoulikari helps you build a mental model of how Git version control works so that you can get the most out of this powerful tool. Whether you're a developer, data professional, technical writer, designer, or product manager, you'll learn the basics of Git in a straightforward and approachable way. Learning Git uses storytelling principles not only to place lessons in a familiar context, but also to make the information more memorable. By introducing information in an incremental manner, this book makes all the content accessible so you don't get bogged down with unknown terms or concepts. This guide is ideal whether you're working on a shared document or managing your own version control project.":
                "Вивчіть основи Git у простий, візуальний і відчутний спосіб. У цій практичній книзі автор Анна Скулікарі допоможе вам побудувати уявну модель того, як працює контроль версій Git, щоб ви могли максимально використати цей потужний інструмент. Незалежно від того, чи є ви розробником, фахівцем з роботи з даними, автором технічних питань, дизайнером або менеджером із продуктів, ви вивчите основи Git у простий і доступний спосіб. Learning Git використовує принципи оповідання не лише для того, щоб розмістити уроки у знайомому контексті, але й щоб зробити інформацію більш запам’ятовуваною. Вводячи інформацію поступово, ця книга робить увесь вміст доступним, щоб ви не загрузли в невідомих термінах чи поняттях. Цей посібник ідеально підходить незалежно від того, чи ви працюєте над спільним документом, чи керуєте власним проектом керування версіями.",
            "Using Scalable Vector Graphics (SVG) for illustrations only scratches the surface of this format’s potential on the web. With this practical guide, you’ll learn how to use SVG not only for illustrations but also as graphical documents that you can integrate into complex HTML5 web pages, and style with custom CSS. Web developers will discover ways to adapt designs by adding data based graphics, dynamic styles, interaction, or animation.":
                "Використання масштабованої векторної графіки (SVG) для ілюстрацій лише дряпає поверхню потенціалу цього формату в Інтернеті. Завдяки цьому практичному посібнику ви дізнаєтесь, як використовувати SVG не лише для ілюстрацій, але й як графічних документів, які можна інтегрувати у складні веб-сторінки HTML5 і стилізувати за допомогою спеціального CSS. Веб-розробники відкриють способи адаптації дизайну шляхом додавання графіки на основі даних, динамічних стилів, взаємодії чи анімації.",
            "SVG is extremely powerful, with its reduced HTTP requests and crispness on any display. It becomes increasingly more interesting as you explore its capabilities for responsive animation and performance boons. When you animate SVG, you must be aware of normal image traits like composition, color, implementation, and optimization. But when you animate, it increases the complexity of each of these factors exponentially. This practical book takes a deep dive into how you can to solve these problems with stability, performance, and creativity in mind.":
                "SVG є надзвичайно потужним із його зменшеною кількістю запитів HTTP та чіткістю на будь-якому дисплеї. Він стає все цікавішим, коли ви досліджуєте його можливості для адаптивної анімації та підвищення продуктивності. Коли ви анімуєте SVG, ви повинні знати про звичайні властивості зображення, такі як композиція, колір, реалізація та оптимізація. Але коли ви анімуєте, це експоненціально збільшує складність кожного з цих факторів. Ця практична книга глибоко занурюється в те, як ви можете вирішити ці проблеми, маючи на увазі стабільність, продуктивність і креативність.",
            "You can do more with Git than just build software. This practical guide delivers a unique people-first approach to version control that also explains how using Git as a focal point can help your team work better together. You’ll learn how to plan and pursue a Git workflow that not only ensures that you accomplish project goals, but also fits the immediate needs and future growth of your team. The first part of the book on structuring workflow is useful for project managers, technical team leads, and CTOs. The second part provides hands-on exercises to help developers gain a better understanding of Git commands.":
                "З Git ви можете робити більше, ніж просто створювати програмне забезпечення. Цей практичний посібник пропонує унікальний підхід до контролю версій, орієнтований на людей, а також пояснює, як використання Git як координаційного центру може допомогти вашій команді краще працювати разом. Ви дізнаєтесь, як планувати та реалізовувати робочий процес Git, який не лише гарантує досягнення цілей проекту, але й відповідає нагальним потребам і майбутньому зростанню вашої команди. Перша частина книги про структурування робочого процесу корисна для керівників проектів, керівників технічних груп і технічних директорів. Друга частина містить практичні вправи, які допоможуть розробникам краще зрозуміти команди Git.",
            "Take your web development skills from browser to server with Node—and learn how to write fast, highly scalable network applications on this JavaScript-based platform. Updated for the latest Node Long Term Support (LTS) and Node Current (6.0) releases, this hands-on edition helps you master Node’s core fundamentals and gain experience with several built-in and contributed modules. Get up to speed on Node’s event-driven, asynchronous I/O model for developing data-intensive applications that are frequently accessed but computationally simple. If you’re comfortable working with JavaScript, this book provides many programming and deployment examples to help you take advantage of server-side development with Node.":
                "Перенесіть свої навички веб-розробки від веб-переглядача до сервера за допомогою Node — і навчіться писати швидкі, високомасштабовані мережеві програми на цій платформі на основі JavaScript. Це практичне видання, оновлене до останніх випусків Node Long Term Support (LTS) і Node Current (6.0), допоможе вам освоїти основні основи Node і отримати досвід роботи з кількома вбудованими та доданими модулями. Ознайомтеся з керованою подіями асинхронною моделлю введення-виведення Node для розробки додатків із інтенсивним об’ємом даних, до яких часто звертаються, але є простими в обчисленні. Якщо вам зручно працювати з JavaScript, ця книга містить багато прикладів програмування та розгортання, які допоможуть вам скористатися перевагами серверної розробки за допомогою Node.",
            "If you know how to use JavaScript in the browser, you already have the skills you need to put JavaScript to work on back-end servers with Node. This hands-on book shows you how to use this popular JavaScript platform to create simple server applications, communicate with the client, build dynamic pages, work with data, and tackle other tasks. Although Node has a complete library of developer-contributed modules to automate server-side development, this book will show you how to program with Node on your own, so you truly understand the platform. Discover firsthand how well Node works as a web server, and how easy it is to learn and use.":
                "Якщо ви знаєте, як використовувати JavaScript у веб-переглядачі, у вас уже є навички, необхідні для роботи JavaScript на внутрішніх серверах із Node. У цій практичній книзі показано, як використовувати цю популярну платформу JavaScript для створення простих серверних програм, спілкування з клієнтом, створення динамічних сторінок, роботи з даними та вирішення інших завдань. Незважаючи на те, що Node має повну бібліотеку модулів, наданих розробниками для автоматизації розробки на стороні сервера, ця книга покаже вам, як програмувати за допомогою Node самостійно, щоб ви справді зрозуміли платформу. Дізнайтеся з перших вуст, наскільки добре Node працює як веб-сервер, і наскільки його легко освоїти та використовувати.",
            "Already have an account?": "Вже є аккаунт?"
        },
    },
}